### ISSUE TITLE
Token Refresh needed?

### ISSUE THREAD

**Issue by kpreiksa** [Azure-Samples/msdocs-flask-web-app-managed-identity#13]
Line 34 of app.py configures the sqlalchemy connection string with a token from DefaultAzureCredential. Will this token refresh automatically (such as to re-connect to the database) once it expires? This seems to hardcode the token into the connection string. How should this be handled?

**Comment by pamelafox** [comment]
An engineer discussed that in this video:
https://learn.microsoft.com/en-us/events/cituscon-an-event-for-postgres-2023/azure-ad-authentication-with-postgresql-flexible-servers-citus-con-an-event-for-postgres-2023

He says that the token-based session will keep working as long as the session is alive, with no token refresh needed. Check timestamp 9:20.
